### ISSUE TITLE
Build failed for Android

### ISSUE THREAD

**Issue by sevafeld** [hypery2k/nativescript-fabric#127]
## Build failed for Android

Trying to add plugin to my NativeScript Angular app and build  it  for android.
It failed to builed with error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '..\android\build-tools\fabric-devtools\build.gradle' line: 12

* What went wrong:
A problem occurred evaluating project ':fabric'.
> Failed to apply plugin [id 'io.fabric']
   > Crashlytics was applied to a project without an Android plugin. Please make sure the Crashlytics plugin is applied after the appropriate Android plugin for your project.
```

## My Environment

**NativeScript version: 4.0.0**
**Plugin version: 1.0.6**
**Java version: 1.8.0_152**
**NodeJS and NPM version: node v8.9.0, npm 6.0.0**
**Platform(s) running: Windows**

**Comment by hypery2k** [comment]
can you try to check if it's working with the next version:
```
tns plugin add nativescript-fabric@next
````

**Comment by sevafeld** [comment]
Next version failed with this exception :

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForF0F1F2F3F4F5Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: Cannot merge new index 69013 into a non-jumbo instruction!nto a non-jumbo instruction!

```

**Comment by hypery2k** [comment]
can you try to set the following in your app.gradle:
```
android {
    ...
    dexOptions {
        jumboMode true
    }

}
```

**Comment by sevafeld** [comment]
It's build successfully now, but crashes immediately when opened :  

```
ActivityManager: Ignoring remove of inactive process: ProcessRecord{2abaa0b 0:com.pumapay.pumawallet/u0a167}
ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.pumapay.pumawallet/com.pumapay.MainActivity} from uid 10023
ActivityManager: applyOptionsLocked: Unknown animationType=0
ActivityManager: Start proc 13461:com.pumapay.pumawallet/u0a167 for activity com.pumapay.pumawallet/com.pumapay.MainActivity
ActivityManager: Slow operation: 88ms so far, now at attachApplicationLocked: after mServices.attachApplicationLocked
ActivityManager:   Force finishing activity com.pumapay.pumawallet/com.pumapay.MainActivity
ActivityManager: Exception thrown during pause
ActivityManager: android.os.DeadObjectException
ActivityManager:        at android.os.BinderProxy.transactNative(Native Method)
ActivityManager:        at android.os.BinderProxy.transact(Binder.java:764)
ActivityManager:        at android.app.IApplicationThread$Stub$Proxy.schedulePauseActivity(IApplicationThread.java:1079)
ActivityManager:        at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1347)
ActivityManager:        at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3779)
ActivityManager:        at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3721)
ActivityManager:        at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3602)
ActivityManager:        at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2124)
ActivityManager:        at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:668)
ActivityManager:        at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:500)
ActivityManager:        at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:376)
ActivityManager:        at com.android.server.am.AppErrors.crashApplication(AppErrors.java:321)
ActivityManager:        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:14375)
ActivityManager:        at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:85)
ActivityManager: Showing crash dialog for package com.pumapay.pumawallet u0
ActivityManager: Process com.pumapay.pumawallet (pid 13461) has died: vis  +99TOP
05-06 04:29:18.368  7176  7198 W zygote  : Long monitor contention with owner Binder:7176_10 (8906) at void com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied()(ActivityManagerService.java:1625) waiters=0 in void com.android.server.am.ActivityManagerService.notifyActivityDrawn(android.os.IBinder) for 119ms
05-06 04:29:18.369  7176  7192 W Looper  : Dispatch took 154ms on android.ui, h=Handler (com.android.server.am.ActivityManagerService$UiHandler) {4ba9af0} cb=null msg=1
05-06 04:29:18.369  7176  7196 W zygote  : Long monitor contention with owner Binder:7176_10 (8906) at void com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied()(ActivityManagerService.java:1625) waiters=3 in int com.android.server.am.ActivityManagerService.broadcastIntent(android.app.IApplicationThread, android.content.Intent, java.lang.String, android.content.IIntentReceiver, int, java.lang.String, android.os.Bundle, java.lang.String[], int, android.os.Bundle, boolean, boolean, int) for 105ms
05-06 04:29:18.372  7176  9043 W zygote  : Long monitor contention with owner Binder:7176_10 (8906) at void com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied()(ActivityManagerService.java:1625) waiters=1 in android.content.ComponentName com.android.server.am.ActivityManagerService.startService(android.app.IApplicationThread, android.content.Intent, java.lang.String, boolean, java.lang.String, int) for 118ms
```

**Comment by hypery2k** [comment]
@EddyVerbruggen: Maybe this related to your changes?

**Comment by sevafeld** [comment]
No adding plugin was the only change
