### ISSUE TITLE
JS Error: Could not find module './fabric.ios.appdelegate

### ISSUE THREAD

**Issue by coltcook** [hypery2k/nativescript-fabric#32]
Hi,

I tried using this in a brand new project using the NS Hello World NG Template on iOS (tns create TestApp --ng), added this plugin and it instantly crashes. I'm on NS CLI 2.5.2, tns-core-modules 2.5.1, and tns-ios 2.5.0

This is the error:
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x1119aa33c -[TNSRuntime executeModule:referredBy:]
2   0x10f9e41c9 main
3   0x113f4268d start
JavaScript stack trace:
1   @file:///app/tns_modules/nativescript-fabric/fabric.js:5:39
JavaScript error:
file:///app/tns_modules/nativescript-fabric/fabric.js:5:39: JS ERROR Error: Could not find module './fabric.ios.appdelegate'. Computed path '/Users/lpw/Library/Developer/CoreSimulator/Devices/97CD0C33-6E21-4975-9612-9333128C860C/data/Containers/Bundle/Application/376E7CC9-4667-4CB5-970C-620C1C9DBE55/CrashPluginTest.app/app/tns_modules/nativescript-fabric/fabric.ios.appdelegate'.

**Comment by hypery2k** [comment]
could you please retry with latest version?

**Comment by dsx1986** [comment]
No, still fails. The js under node_modules/nativescript-fabric/fabric.io.appdelegate.js was renamed to fabric.delegate under platforms/ios/{app_name}/tns_modules/fabric.appdelegate

**Comment by hypery2k** [comment]
are you using the AoT build in angular?

**Comment by hypery2k** [comment]
Did you installed via npm or manually copy the files?

**Comment by twojtylak** [comment]
same here. I tried the dev and the stable version but in both cases I got the error.
I installed the module via tns plugin add

**Comment by hypery2k** [comment]
I'm not able to reproduce your error.

did you cleaned the node_modules before?

**Comment by dsx1986** [comment]
If you go  platforms/ios/{app_name}/tns_modules/nativescript-fabric, do you see fabric.appdelegate.js or fabric.io.appdelegate.js? In fabric.io.js it has reference to fabric.io.delegate.js

**Comment by hypery2k** [comment]
I'm using an AoT build, so not having any tns_modules. Could you please try wiping out your node_modules folder?

**Comment by twojtylak** [comment]
Thank you guys. 
Unfortunately it is still not working after 
- removing the node_modules folder
- running tns prepare ios
- running tns run ios 

The directory structure  in nativescript-fabric is the following

<img width="342" alt="nativescript-fabric" src="https://cloud.githubusercontent.com/assets/16890929/24041915/dd7d13a2-0b0f-11e7-962b-cedc1e235507.png">
 
In Xcode I receive the following error

> ***** Fatal JavaScript exception - application has been terminated. *****
> Native stack trace:
> 2017-03-17 12:40:16.971781 testapp
> [929:267183] 1   0x10076de20 -[TNSRuntime executeModule:referredBy:]
> 1   0x10076de20 -[TNSRuntime executeModule:referredBy:]
> 2017-03-17 12:40:16.973790 testapp
> [929:267183] 2   0x1000dbbb4 main
> 2   0x1000dbbb4 main
> 2017-03-17 12:40:16.973952 testapp
> [929:267183] 3   0x180fd45b8 <redacted>
> 3   0x180fd45b8 <redacted>
> JavaScript stack trace:
> 1   @file:///app/tns_modules/nativescript-fabric/fabric.js:5:39
> JavaScript error:
> 2017-03-17 12:40:16.974561 testapp
> [929:267183] file:///app/tns_modules/nativescript-fabric/fabric.js:5:39: JS ERROR Error: Could not find module './fabric.ios.appdelegate'. Computed path '/var/containers/Bundle/Application/EC3--F
> /testapp
> .app/app/tns_modules/nativescript-fabric/fabric.ios.appdelegate'.
> file:///app/tns_modules/nativescript-fabric/fabric.js:5:39: JS ERROR Error: Could not find module './fabric.ios.appdelegate'. Computed path '/var/containers/Bundle/Application/EC3--F
> /testapp
> .app/app/tns_modules/nativescript-fabric/fabric.ios.appdelegate'.

In my main.ts I defined following:
`import {Fabric} from 'nativescript-fabric';
`
`Fabric.init();`

Did I miss something? Do you have any ideas what might be wrong

Thank you

**Comment by danielgek** [comment]
@hypery2k i'm having this issue too with version 0.2.2

**Comment by danielgek** [comment]
ps: not using aot

**Comment by hypery2k** [comment]
Ok, take a look at it tomorrow

**Comment by danielgek** [comment]
@hypery2k thanks

**Comment by zakdances** [comment]
Same problem here. Using `0.2.2` without aot

**Comment by hypery2k** [comment]
Could you try `nativescript-fabric@0.2.2-develop-54`?

**Comment by danielgek** [comment]
@hypery2k it's kinda working xD

So if i remove the pugin and add again i got this error(this hook it's not coping the pod spec)

```
tns plugin remove nativescript-fabric
tns plugin add nativescript-fabric@0.2.2-develop-54
```

```
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Configure\ Fabric /Users/danielgek/Library/Developer/Xcode/DerivedData/Ces-corxubxlidkmcxgcjcivwcxyquzp/Build/Intermediates/Ces.build/Debug-iphoneos/Ces.build/Script-61B10A2BB7C1417EAEA04F9E.sh
(1 failure)
Command xcodebuild failed with exit code 65

```

but if i add the stable version of the plugin and then update the plugin to the test version it works ok

```
tns plugin add nativescript-fabric
tns plugin add nativescript-fabric@0.2.2-develop-54
```

**Comment by danielgek** [comment]
that was on ios

**Comment by danielgek** [comment]
on android i'm getting this error:

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{pt.minsaude.spms.ces/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onStart failed

ReferenceError: io is not defined
File: "file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 702, column: 18

StackTrace: 
	Frame: function:'', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/nativescript-fabric/fabric.js', line: 25, column: 21
	Frame: function:'Observable.notify', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 149, column: 23
	Frame: function:'onActivityStarted', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/application/application.js', line: 71, column: 24
	Frame: function:'ActivityCallbacksImplementation.onStart', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 702, column: 19
	Frame: function:'NativeScriptActivity.onStart', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 19, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2805)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6408)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:232)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
Caused by: com.tns.NativeScriptException: 
Calling js method onStart failed

ReferenceError: io is not defined
File: "file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 702, column: 18

StackTrace: 
	Frame: function:'', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/nativescript-fabric/fabric.js', line: 25, column: 21
	Frame: function:'Observable.notify', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 149, column: 23
	Frame: function:'onActivityStarted', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/application/application.js', line: 71, column: 24
	Frame: function:'ActivityCallbacksImplementation.onStart', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 702, column: 19
	Frame: function:'NativeScriptActivity.onStart', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 19, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
	at com.tns.NativeScriptActivity.onStart(Unknown Source:15)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1315)
	at android.app.Activity.performStart(Activity.java:6784)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2709)
	... 9 more
```

so i gess it's not adding the library too, maybe this has to do with hook ?

**Comment by hypery2k** [comment]
Thanks, I will take a look at it later

**Comment by danielgek** [comment]
@hypery2k you welcome, if you need more debug info just ping me

**Comment by hypery2k** [comment]
No thanks it's enough, I try to setup CI tests for this issue to verify it automatically in the future

**Comment by hypery2k** [comment]
you could try doing a fresh install, meaning remove platforms and hooks, run npm install with the @next version and build ios and android

**Comment by danielgek** [comment]
@hypery2k yes, give me a few minutes

**Comment by danielgek** [comment]
@hypery2k still giving the same error:

Commands executed:

```
tns plugin remove nativescript-fabric
rm -rf platforms/
tns plugin add nativescript-fabric@next
tns run android
tns run ios
```

after uninstalling the plugin on the first i manually verified that the hook is not there


On android:
```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{pt.minsaude.spms.ces/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onStart failed

ReferenceError: io is not defined
File: "file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 702, column: 18

StackTrace: 
	Frame: function:'', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/nativescript-fabric/fabric.js', line: 25, column: 21
	Frame: function:'Observable.notify', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 149, column: 23
	Frame: function:'onActivityStarted', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/application/application.js', line: 71, column: 24
	Frame: function:'ActivityCallbacksImplementation.onStart', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 702, column: 19
	Frame: function:'NativeScriptActivity.onStart', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 19, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2805)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6408)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:232)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
Caused by: com.tns.NativeScriptException: 
Calling js method onStart failed

ReferenceError: io is not defined
File: "file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 702, column: 18

StackTrace: 
	Frame: function:'', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/nativescript-fabric/fabric.js', line: 25, column: 21
	Frame: function:'Observable.notify', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 149, column: 23
	Frame: function:'onActivityStarted', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/application/application.js', line: 71, column: 24
	Frame: function:'ActivityCallbacksImplementation.onStart', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 702, column: 19
	Frame: function:'NativeScriptActivity.onStart', file:'file:///data/data/pt.minsaude.spms.ces/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 19, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
	at com.tns.NativeScriptActivity.onStart(Unknown Source:15)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1315)
	at android.app.Activity.performStart(Activity.java:6784)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2709)
	... 9 more
```
on iOS:

```
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Configure\ Fabric /Users/danielgek/Library/Developer/Xcode/DerivedData/Ces-corxubxlidkmcxgcjcivwcxyquzp/Build/Intermediates/Ces.build/Debug-iphonesimulator/Ces.build/Script-27A39E25648146C8A093E261.sh
(1 failure)
Command xcodebuild failed with exit code 65
```

So i guess the hook it's still not working

**Comment by hypery2k** [comment]
So initial iOS issue seems to be resolved. Within my test app android and iOS is working fine. For any new issue, please open up a new issue. Thanks
