### ISSUE TITLE
Crash when logging object

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/nativescript-fabric#51]
```
04-06 20:24:13.647 26357 26357 W System.err: TimeoutError: Timeout has occurred
04-06 20:24:13.647 26357 26357 W System.err: File: "file:///data/data/myapp/files/app/vendor.js, line: 58795, column: 24
04-06 20:24:13.647 26357 26357 W System.err: StackTrace:
04-06 20:24:13.647 26357 26357 W System.err:  Frame: function:'module.exports.Zone.runGuarded', file:'file:///data/data/myapp/files/app/vendor.js', line: 58795, column: 25
04-06 20:24:13.647 26357 26357 W System.err:  Frame: function:'', file:'file:///data/data/myapp/files/app/vendor.js', line: 58767, column: 29
04-06 20:24:13.647 26357 26357 W System.err:  Frame: function:'run', file:'file:///data/data/myapp/files/app/vendor.js', line: 60839, column: 13
04-06 20:24:13.647 26357 26357 W System.err:  at com.tns.Runtime.callJSMethodNative(Native Method)
04-06 20:24:13.647 26357 26357 W System.err:  at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
04-06 20:24:13.647 26357 26357 W System.err:  at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
04-06 20:24:13.647 26357 26357 W System.err:  at com.tns.Runtime.callJSMethod(Runtime.java:1047)
04-06 20:24:13.647 26357 26357 W System.err:  at com.tns.Runtime.callJSMethod(Runtime.java:1028)
04-06 20:24:13.647 26357 26357 W System.err:  at com.tns.Runtime.callJSMethod(Runtime.java:1018)
04-06 20:24:13.648 26357 26357 W System.err:  at com.tns.gen.java.lang.Runnable.run(java.lang.Runnable.java)
04-06 20:24:13.648 26357 26357 W System.err:  at android.os.Handler.handleCallback(Handler.java:739)
04-06 20:24:13.648 26357 26357 W System.err:  at android.os.Handler.dispatchMessage(Handler.java:95)
04-06 20:24:13.648 26357 26357 W System.err:  at android.os.Looper.loop(Looper.java:148)
04-06 20:24:13.648 26357 26357 W System.err:  at android.app.ActivityThread.main(ActivityThread.java:5525)
04-06 20:24:13.648 26357 26357 W System.err:  at java.lang.reflect.Method.invoke(Native Method)
04-06 20:24:13.648 26357 26357 W System.err:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
04-06 20:24:13.648 26357 26357 W System.err:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
04-06 20:24:13.654 26357 26357 W System.err: com.tns.NativeScriptException:
04-06 20:24:13.655 26357 26357 W System.err: Error: Cannot convert object to Ljava/lang/Throwable; at index 0
04-06 20:24:13.655 26357 26357 W System.err: File: "file:///data/data/myapp/files/app/bundle.js, line: 18199, column: 75
04-06 20:24:13.655 26357 26357 W System.err: StackTrace:
04-06 20:24:13.655 26357 26357 W System.err:  Frame: function:'', file:'file:///data/data/myapp/files/app/bundle.js', line: 18199, column: 76
04-06 20:24:13.655 26357 26357 W System.err:  Frame: function:'module.exports.Observable.notify', file:'file:///data/data/myapp/files/app/vendor.js', line: 13210, column: 23
04-06 20:24:13.655 26357 26357 W System.err:  Frame: function:'module.exports.global.__onUncaughtError', file:'file:///data/data/myapp/files/app/vendor.js', line: 5627, column: 18
04-06 20:24:13.655 26357 26357 W System.err:  at com.tns.Runtime.passUncaughtExceptionToJsNative(Native Method)
04-06 20:24:13.655 26357 26357 W System.err:  at com.tns.Runtime.passUncaughtExceptionToJs(Runtime.java:69)
04-06 20:24:13.655 26357 26357 W System.err:  at com.tns.NativeScriptUncaughtExceptionHandler.uncaughtException(NativeScriptUncaughtExceptionHandler.java:39)
04-06 20:24:13.655 26357 26357 W System.err:  at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:38)
04-06 20:24:13.655 26357 26357 W System.err:  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
04-06 20:24:13.655 26357 26357 W System.err:  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
```

**Comment by hypery2k** [comment]
seems to be caused by [this line ](https://github.com/hypery2k/nativescript-fabric/blob/master/fabric.android.ts#L49)

**Comment by hypery2k** [comment]
unit tests needed
