### ISSUE TITLE
Plugin not working on Android Nativescript 3.0

### ISSUE THREAD

**Issue by giorgiopiatti** [hypery2k/nativescript-fabric#65]
I've made a few tests, but unfortunately the plugin is not working on Android with Nativescript 3.0.
I didn't understand if the plugin is already compatible or not, so I creare this issue, maybe it will be useful.

I explain me better: the plugin successful initialize with Fabric when this is called:
```
CrashlyticsAndroidPlugin.prototype.init = function () {
        var _this = this;
        try {
            if (application.android) {
                application.android.on('activityStarted', function (activityEventData) {
                    io.fabric.sdk.android.Fabric.with(new io.fabric.sdk.android.Fabric.Builder(activityEventData.activity)
                        .kits([
                        new com.crashlytics.android.Crashlytics(),
                        new com.crashlytics.android.answers.Answers()
                    ])
                        .debuggable(true)
                        .build());
                    _this.initDone = true;
                });
                application.on('uncaughtError', function (args) {
                    if (!args.android) {
                        com.crashlytics.android.Crashlytics.getInstance().core.log(android.util.Log.ERROR, 'ERROR', JSON.stringify(args));
                    }
                    else {
                        com.crashlytics.android.Crashlytics.getInstance().core.logException(_this.getErrorDetails(args));
                    }
                });
            }
        }
        catch (e) {
            console.error('Unknown error during init of Fabric', e);
        }
    };
```
But when i try to log some data with one of these function:
```
CrashlyticsAndroidPlugin.prototype.logError = function (error, msg) {
        if (this.initDone) {
            try {
                if (!error.android) {
                    com.crashlytics.android.Crashlytics.getInstance().core.log(android.util.Log.ERROR, 'ERROR', msg);
                    com.crashlytics.android.Crashlytics.getInstance().core.log(JSON.stringify(error));
                }
                else {
                    com.crashlytics.android.Crashlytics.getInstance().core.logException(this.getErrorDetails(error));
                }
                console.log('Error send'); //Adding this to debug purpose
            }
            catch (e) {
                console.error('Unknown logging error in Fabric', e);
            }
        }
    };

```
Nothing happens, any message were prompt.

It seems a great plugin!  I'm waiting to use it ;)
By the way is use Nativescript with Angular.

**Comment by hypery2k** [comment]
thanks for reporting, but please share your concrete code and not the plugin source code

**Comment by hypery2k** [comment]
my end2end app is working in iOS and Android with angular, see [here](https://github.com/hypery2k/nativescript-fabric/tree/develop/test/e2e).

You can give the latest develop version a shot `tns plugin add nativescript-fabric@next`

**Comment by giorgiopiatti** [comment]
With the newest version all seems to work but sometimes when initializing Fabric all crash.
It can be connected with another view Error that I was solving.
```
Error: java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
    io.fabric.sdk.android.Fabric.singleton(Fabric.java:273)
    io.fabric.sdk.android.Fabric.getKit(Fabric.java:524)
    com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:188)
    com.tns.Runtime.passUncaughtExceptionToJsNative(Native Method)
    com.tns.Runtime.passUncaughtExceptionToJs(Runtime.java:67)
    com.tns.NativeScriptUncaughtExceptionHandler.uncaughtException(NativeScriptUncaughtExceptionHandler.java:33)
    java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
    java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
    at Object.callback (file:///data/data/com.ProBooster/files/app/tns_modules/nativescript-fabric/fabric.js:43:61)
    at Observable.notify (file:///data/data/com.ProBooster/files/app/tns_modules/tns-core-modules/data/observable/observable.js:103:23)
    at Object.global.__onUncaughtError (file:///data/data/com.ProBooster/files/app/tns_modules/tns-core-modules/application/application-common.js:63:12)
```

**Comment by hypery2k** [comment]
can you post your complete code?

Are you using the [angular module](https://github.com/hypery2k/nativescript-fabric#angular)?

**Comment by hypery2k** [comment]
closed due to inactivity
