### ISSUE TITLE
Error: upload to Crashlytics

### ISSUE THREAD

**Issue by mikraus94** [hypery2k/nativescript-fabric#68]
Hello,

I have issue while uploading android app to Crashlytics.

`Crashlytics halted compilation because it can't extract Crashlytics build info from the APK`

I followed your tutorial. Can you help me?

Thank you

**Comment by hypery2k** [comment]
try removing the platforms folder first

**Comment by mikraus94** [comment]
I tried.

I have nativescript 2.5.4, tns-core-modules 2.5.2.

I've added meta data to android manifest, created fabric.json in project root and add import to modules and init fabric in main.ts.

While I'm trying to upload apk to crashlytics by fastlane, I'll get this error

```
WARN - Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/kraus/PhpstormProjects/bavic-buildserver/Exports/zlepsito.apk
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/kraus/PhpstormProjects/bavic-buildserver/Exports/zlepsito.apk
	at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:64)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
	... 2 more
```

**Comment by hypery2k** [comment]
could you remove hooks also? My [sample app](https://github.com/hypery2k/nativescript-fabric/tree/master/test/e2e) is working. So having no clue why you got this error.

**Comment by alexdohmen** [comment]
@hypery2k facing the same issue on a fresh build (removed hooks & platforms)
Error shows up on apk upload to crashlytics via fastlane

(fastlane 2.46.1, crashlytics 2.8.6, tns 3.1.0)

It is the last step in a cont. deploy pipeline. Build is done via tns, upload to fabric via fastlane/crashlytics.

**Comment by alexdohmen** [comment]
@mikraus94 were you able to solve this issue in any way?

**Comment by alexdohmen** [comment]
ok, seems that sdk is looking for a generated "assets/crashlytics-build.properties" which is missing
